### ISSUE TITLE
README

### ISSUE THREAD

**Issue by gavla** [Dahlgren/tvos-plex-backend#1]
Hi is there any chance of a read file possibly with basic instructions or even just in the reply as my java is worse than beginner lvl and i'd really love to get this working on my new apple tv box

Thanks

**Comment by Dahlgren** [comment]
Done!

**Comment by gavla** [comment]
Thanks for the README although I'm still having issues to start the server with this error

```
    { [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
/Users/ga*****/Desktop/tvos-plex-backend-master/node_modules/plex-api/lib/api.js:35
        throw new TypeError('Invalid Plex Server hostname');
        ^

TypeError: Invalid Plex Server hostname
    at new PlexAPI (/Users/ga****/Desktop/tvos-plex-backend-master/node_modules/plex-api/lib/api.js:35:15)
    at Object.<anonymous> (/Users/ga****/Desktop/tvos-plex-backend-master/app.js:9:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

any input would be appreciated

**Comment by Dahlgren** [comment]
You haven't created the `.env` file, see step 3 in https://github.com/Dahlgren/tvos-plex-backend#how-to-use-it

It should contain the following,

```
HOSTNAME=ip or dns to your Plex Server
PORT=port that your Plex Server uses
USERNAME=your myPlex username
PASSWORD=your myPlex password
```

**Comment by gavla** [comment]
yeah thanks for the reply, I've got the process.env in the root dir with the above details but still get this error

**Comment by Dahlgren** [comment]
No, the file should be called `.env`, not `process.env`. The content should be a simple key-value as stated in the example above.

**Comment by gavla** [comment]
Awesome thanks thats sorted it, great work BTW
